org: jarrettmapitin
app: serverless-express-typescript
service: serverless-express-typescript

custom:
  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  lambdaHashingVersion: 20201221 # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2

functions:
  app:
    handler: src/index.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  individually: true

plugins:
  # - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-offline
